#!/bin/bash -e
esp_path="/efi/BOOT/Arch"
current_img="linux-signed.efi"
backup_img="linux-signed-bkp.efi"
mkdir -p $esp_path

kernels=()
dracut_update=0

while read -r line; do
    if [[ $line != 'usr/lib/modules/'+([^/])'/pkgbase' ]]; then
		dracut_update=1 # Dracut files have been updated
        continue 
    fi

    read -r pkgbase < "/${line}"
	kernels+=("${pkgbase}")
done

if (( dracut_update )); then
	kernels=()
	for file in /lib/modules/*/pkgbase; do
		if read -r pkgbase &> /dev/null < "$file"; then
			kernels+=("${pkgbase}")
		fi
	done
fi

for kernel in "${kernels[@]}"; do
	path="$(grep -lE "^${kernel}\$" /usr/lib/modules/*/pkgbase)"
	version=$(basename "${path%/pkgbase}")
    read -r pkgbase < "$path"

    echo "Backing up current image"
    cp -f $esp_path/$current_img $esp_path/$backup_img

    echo ":: Building linux image $kernel ($version)"
    dracut -f -v --kver "${version}" $esp_path/$current_img
done
